version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    groups:
      nuget:
        patterns: ['*']
    commit-message:
      prefix: FIX

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ['*']
    commit-message:
      prefix: FIX
