using SkiaSharp.Skottie;

namespace DrawEM.App.Presentation.Effects;

/// <summary>
/// The S4-03.1 probe's synthetic Lottie loads, generated by <c>tools/EffectProbeAnimations/generate.py</c>:
/// 120 tumbling confetti pieces on a 1920x1080 canvas for 3 s (Monitor), and two rings on a 240x240 canvas
/// for 2 s (Cursor). They measure speed only; S4-03 replaces them with the built-in effects.
/// </summary>
public static class EffectProbeAnimations
{
    public static Animation Load(EffectProbePlacement placement)
    {
        var name = placement == EffectProbePlacement.Cursor ? "probe-focus-ring.json" : "probe-confetti.json";
        using var stream = typeof(EffectProbeAnimations).Assembly.GetManifestResourceStream(
            $"DrawEM.App.Presentation.Effects.ProbeAnimations.{name}")
            ?? throw new InvalidOperationException($"The probe animation {name} is not embedded.");
        return Animation.TryCreate(stream, out var animation) && animation is not null
            ? animation
            : throw new InvalidOperationException($"The probe animation {name} is not a valid Lottie file.");
    }
}
